# Generated by Django 4.2 on 2024-04-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abnormal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
                ("floor_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "abnormal", "managed": False,},
        ),
        migrations.CreateModel(
            name="Accessrecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.IntegerField()),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
                ("building_id", models.BigIntegerField(blank=True, null=True)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "accessrecord", "managed": False,},
        ),
        migrations.CreateModel(
            name="Backrecords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
                (
                    "userid",
                    models.IntegerField(blank=True, db_column="userId", null=True),
                ),
            ],
            options={"db_table": "backrecords", "managed": False,},
        ),
        migrations.CreateModel(
            name="Buildings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_comment="楼宇名称", max_length=255)),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "buildings", "managed": False,},
        ),
        migrations.CreateModel(
            name="Cleaners",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_comment="保洁员姓名", max_length=255)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_comment="保洁员电话", max_length=255, null=True
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "cleaners", "managed": False,},
        ),
        migrations.CreateModel(
            name="Cleanrecords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
                (
                    "userid",
                    models.IntegerField(blank=True, db_column="userId", null=True),
                ),
            ],
            options={"db_table": "cleanrecords", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={"db_table": "django_migrations", "managed": False,},
        ),
        migrations.CreateModel(
            name="Evaluates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(db_comment="评价分数")),
                (
                    "note",
                    models.CharField(
                        blank=True, db_comment="评价备注", max_length=255, null=True
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
                (
                    "userid",
                    models.IntegerField(blank=True, db_column="userId", null=True),
                ),
            ],
            options={"db_table": "evaluates", "managed": False,},
        ),
        migrations.CreateModel(
            name="Faculties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_comment="院系名称", max_length=255)),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "faculties", "managed": False,},
        ),
        migrations.CreateModel(
            name="Floors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.IntegerField(blank=True, db_comment="楼层", null=True)),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "floors", "managed": False,},
        ),
        migrations.CreateModel(
            name="Getuprecords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
                (
                    "userid",
                    models.IntegerField(blank=True, db_column="userId", null=True),
                ),
            ],
            options={"db_table": "getuprecords", "managed": False,},
        ),
        migrations.CreateModel(
            name="Majors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_comment="专业名称", max_length=255)),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "majors", "managed": False,},
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(blank=True, db_comment="房间号", null=True),
                ),
                ("status", models.IntegerField(db_comment="宿舍状态，可入住为1，不可入住为2")),
                (
                    "peoplenum",
                    models.IntegerField(db_column="peopleNum", db_comment="房间最大人数"),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "rooms", "managed": False,},
        ),
        migrations.CreateModel(
            name="Tokens",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "userid",
                    models.IntegerField(blank=True, db_column="userId", null=True),
                ),
            ],
            options={"db_table": "tokens", "managed": False,},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sex",
                    models.IntegerField(
                        blank=True, db_comment="性别, 0：男, 1：女", null=True
                    ),
                ),
                (
                    "checktime",
                    models.DateTimeField(
                        blank=True,
                        db_column="checkTime",
                        db_comment="入住宿舍时间",
                        null=True,
                    ),
                ),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "users", "managed": False,},
        ),
        migrations.CreateModel(
            name="Visitors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_comment="访客姓名", max_length=255)),
                ("phone", models.CharField(db_comment="访客电话", max_length=255)),
                (
                    "idnumber",
                    models.CharField(
                        db_column="idNumber", db_comment="访客身份证号", max_length=255
                    ),
                ),
                ("sex", models.IntegerField(db_comment="访客性别, 0：男, 1：女")),
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "deletedat",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={"db_table": "visitors", "managed": False,},
        ),
        migrations.CreateModel(
            name="Admins",
            fields=[
                ("createdat", models.DateTimeField(db_column="createdAt")),
                ("updatedat", models.DateTimeField(db_column="updatedAt")),
                (
                    "buildingid",
                    models.OneToOneField(
                        db_column="buildingId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="old.buildings",
                    ),
                ),
            ],
            options={"db_table": "admins", "managed": False,},
        ),
    ]
